{{ if .ImagePullSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: open-cluster-management-image-pull-credentials
  namespace: {{ .AddonInstallNamespace }}
{{- if eq .InstallMode "Hosted" }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{- end }}
type:  kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ .ImagePullSecretData }}
{{ end }}
