{{ if eq .InstallMode "Hosted" }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: managed-serviceaccount-kubeconfig-provisioner
  namespace: {{ .AddonInstallNamespace }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{ end }}
